name: base
channels:
- conda-forge
dependencies:
- adlfs=0.7.5  # Prevent azure blob errors, not hard req.
- dask
- click
- cftime
- fsspec=2021.5.0  # Prevent azure blob errors, not hard req.
- gcsfs
- numpy
- pip
- pytest
- python=3.9
- s3fs
- xarray
- xesmf
- bottleneck
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@feature/add_spatial_disaggregation_recipe
  - git+https://github.com/Ouranosinc/xclim@d1e654cf59a5d5761f5586bca1102a1590ae6e32
