name: base
channels:
- conda-forge
dependencies:
- adlfs
- dask
- click
- cftime
- intake  # Not direct dependency. Used in docker environment.
- intake-esm  # Not direct dependency. Used in docker environment.
- gcsfs
- netcdf4
- numpy
- papermill  # Not direct dependency. Used in docker environment.
- pip
- pytest
- python=3.9
- s3fs
- xarray
- xesmf
- bottleneck
- zarr
- pip:
  - git+https://github.com/ClimateImpactLab/xclim@63023d27f89a457c752568ffcec2e9ce9ad7a81a
