name: base
channels:
- conda-forge
dependencies:
- adlfs=0.6
- click
- cftime
- fsspec=0.8.7 # Pinned req. for adlfs < 0.7
- numpy
- pip
- pytest
- python=3.8
- rechunker
- xarray
- xesmf
- esmpy=8.0.1=nompi_py38h5410a82_2  # Not direct dep. Dep of xesmf.
- bottleneck
- xclim
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@pointwisedownscaler_interimfix
