name: base
channels:
- conda-forge
dependencies:
- adlfs=0.6
- click
- cftime
- fsspec=0.8.7 # Pinned req. for adlfs < 0.7
- gcsfs
- numpy
- pip
- pytest
- python=3.8
- s3fs
- xarray=0.17.0 # Pinned for bug in dodola.services.rechunk
- xesmf
- bottleneck
- xclim
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@feature/add_spatial_disaggregation_recipe
