name: base
channels:
- conda-forge
dependencies:
- adlfs=0.7.5  # Prevent azure blob errors, not hard req.
- dask=2021.6.0
- click=8.0.1
- cftime=1.5.0
- intake=0.6.2  # Not direct dependency. Used in docker environment.
- intake-esm=2021.1.15  # Not direct dependency. Used in docker environment.
- fsspec=2021.5.0  # Prevent azure blob errors, not hard req.
- gcsfs=2021.5.0
- netcdf4=1.5.7
- numpy=1.20.3
- pandas=1.2.5  # Not direct dependency, workaround to time slice bug in #96
- papermill=2.3.3  # Not direct dependency. Used in docker environment.
- pip=21.1.2
- pytest=6.2.4
- python=3.9
- s3fs=2021.5.0
- xarray=0.19.0
- xesmf=0.5.3
- bottleneck=1.3.2
- zarr=2.8.3
- pip:
  - git+https://github.com/dgergel/xsd@458f292dab6e8a6584659e97a66c37e028da2b7a
  - git+https://github.com/ClimateImpactLab/xclim@c5507ba29c19f957270789fd790ffe6c315a3daa
