name: base
channels:
- conda-forge
- nesii
dependencies:
- adlfs
- click
- cftime
- fsspec
- numpy
- pip
- pytest
- python=3.8
- rechunker
- xarray
- xesmf
- bottleneck
- xclim
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@pointwisedownscaler_interimfix
