name: base
channels:
- conda-forge
dependencies:
- adlfs
- click
- cftime
- numpy
- pip
- pytest
- python=3.8
- xarray
- bottleneck
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@pointwisedownscaler_interimfix
  - xclim
