name: base
channels:
- conda-forge
dependencies:
- adlfs=2022.2.0
- dask=2022.2.0
- click=8.0.3
- cftime=1.5.2
- intake=0.6.5  # Not direct dependency. Used in docker environment.
- intake-esm=2021.8.17  # Not direct dependency. Used in docker environment.
- gcsfs=2022.1.0
- numpy=1.22.2
- papermill=2.3.4  # Not direct dependency. Used in docker environment.
- pip=22.0.3
- pytest=7.0.1
- pytest-cov
- python=3.9
- s3fs=2022.1.0
- xarray=0.21.1
- xesmf=0.6.2
- bottleneck=1.3.2
- zarr=2.11.0
- pip:
  - git+https://github.com/ClimateImpactLab/xclim@63023d27f89a457c752568ffcec2e9ce9ad7a81a
