name: base
channels:
- conda-forge
dependencies:
- adlfs
- click
- cftime
- fsspec
- gcsfs
- numpy
- pip
- pytest
- python=3.9
- s3fs
- xarray
- xesmf
- bottleneck
- zarr
- pip:
  - git+https://github.com/dgergel/xsd@feature/add_spatial_disaggregation_recipe
  - git+https://github.com/Ouranosinc/xclim@92ba9f1fb2f45dd65c52fd35fbfff9d80ac9ee54  #spec commit from @sdba-ufunc
