# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: dodola Documentation
repo_url: "https://github.com/climateimpactlab/dodola"

theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "numpy"
            summary: true
            separate_signature: true
            show_object_full_path: true
            show_root_toc_entry: false
  - search

markdown_extensions:
  - "pymdownx.snippets"

nav:
  - Home: index.md
  - API Reference:
      - dodola.cli: cli.md
      - dodola.core: core.md
      - dodola.repository: repository.md
      - dodola.services: services.md
  - Changelog: changelog.md
