name: Build, push dev

on:
  push:
    branches:
    - "main"

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build container
      run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev
    - name: Test container package
      run: |
        docker run ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev pytest -v --pyargs dodola
    - name: Test container CLI
      run: |
        docker run ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev dodola --help
    - name: Push to registry
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev
