name: Build, test, push container

on:
  push:
    branches: "main"

jobs:
  buildcontainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev
    - name: Test container package
      run: |
        docker run ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev pytest -v --pyargs dodola
    - name: Test container CLI
      run: |
        docker run ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev dodola --help
    - name: Push to registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/dodola:dev
